### PR TITLE
Fix 2 issues with Git Gui menus

### LINKED ISSUE #253: git gui menus do not work properly
### Operating System

Arch Linux

### Wayland Compositor

Niri

### Describe the issue.

When launching `git gui` the tk gui wrapper for git `/usr/lib/git-core/git-gui` the menu system is not working 

### Steps to reproduce

run git gui, click anything in the menus and instead of showing up in the right spot they open in dedicated windows.

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

### PR DESCRIPTION
**Pull request by En-En-Code**
Partially resolves #253. Apparently there is also a scaling issue, but I do not understand it and the issue author has not responded in some time.

### CODE REVIEW

File: src/server/event.rs [hunk 1]
```diff
@@ -460,6 +460,40 @@ impl Event for client::wl_pointer::Event {
...
+            };
+            let PendingEnter(client::wl_pointer::Event::Enter {
+                serial,
+                surface,
+                surface_x,
+                surface_y,
+            }) = pe.deref()
+            else {
+                unreachable!();
+            };
```
Comment (Supreeeme) [inline src/server/event.rs]: Is this else needed? This seems like an irrefutable pattern.

Comment (En-En-Code) [reply src/server/event.rs]: `PendingEnter` is a wrapper around the `wl_pointer::Event` enum, which has more than just the `Enter` variant, even if that is all we store in it. Just I could redefine `PendingEnter` if we really don't it.
